# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "centos/7"

  disks_dir = File.join(File.dirname(File.expand_path(__FILE__)), "disks")
  FileUtils.mkdir_p(disks_dir)

  config.vm.provider "virtualbox" do | p |
    p.customize ["storagectl", :id, "--name", "SATA Controller", "--add", "sata"]
    for i in 1..4
      disk_name = "hdd_drive#{i}.vdi" % [i]
      disk_path = File.join(disks_dir, disk_name)
      if !File.exist?(disk_path)
        p.customize ["createhd", "--filename", disk_path, "--size", 300]
      end
      p.customize ["storageattach", :id, "--storagectl", "SATA Controller", "--port", i, "--device", 0, "--type", "hdd", "--medium", disk_path]
    end
  end
  
  config.vm.provision "shell", path: "script.sh"
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
